### ISSUE TITLE
Some more documentation

### ISSUE THREAD

**Issue by piuccio** [artberri/rollup-plugin-istanbul#11]
Thanks for the plugin, it works really well. I don't know where to put this (maybe you want to create a wiki) but this is what I've done to get it working with mocha.

`rollup.config.test.js`
```js
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import babel from 'rollup-plugin-babel';
import istanbul from 'rollup-plugin-istanbul';

export default {
	entry: 'src/index.js',
	format: 'cjs',
	dest: 'tmp/bundle.test.js',
	plugins: [
		babel(),
		istanbul({
			exclude: ['test/*.js', 'node_modules/**/*']
		}),
		nodeResolve({ jsnext: true }),
		commonjs()
	]
};
```

The tests can now import the bundled version

`random.test.js`
```js
import {expect} from 'chai';
import {Something} from '../tmp/bundle.test.js';

describe('something', function () {
	it('works', function () {});
});
```

You'll need a custom reporter
`istanbul.reporter.js`
```js
const instanbul = require('istanbul');
const MochaSpecReporter = require('mocha/lib/reporters/spec');

module.exports = function (runner) {
	const collector = new instanbul.Collector();
	const reporter = new instanbul.Reporter();
	reporter.addAll([ 'lcov', 'json' ]);
	new MochaSpecReporter(runner);

	runner.on('end', function () {
		collector.add(global.__coverage__);

		reporter.write(collector, true, function () {
			console.log('report generated');
		});
	});
};
```

Then you can run your tests with
```
rollup -c rollup.config.test.js && mocha --reporter test/istanbul.reporter.js test
```

I output coverage in `./coverage` as html and json, so you can use something like

```
istanbul check-coverage --statements 85 --branches 70 --functions 100 --lines 90
```

Cheers

**Comment by artberri** [comment]
I added a link to this issue on the README.md, thank you @piuccio !

**Comment by paulfalgout** [comment]
Good example in this boilerplate for mocha as well https://github.com/rollup/rollup-starter-project

**Comment by brettz9** [comment]
My reports are showing the `dist` files coverage imported by the test script--is there a way to get the coverage report to only look at my `src` files coverage (and adding `dist`, `dist/**`, or `dist/*.js` didn't help)?

**Comment by brettz9** [comment]
I'm also not getting `global.__coverage__` to be defined so getting errors...

**Comment by brettz9** [comment]
Seems the issue with `global.__coverage__` was in my using `esm`.
