### ISSUE TITLE
Exporting constants causes karma to crash and fail silently

### ISSUE THREAD

**Issue by ccampbell** [artberri/rollup-plugin-istanbul#2]
Im not sure this is specifically related to this plugin.

Karma config is similar to the one in your README. 

To reproduce

1. Create a test file `test/something.js` that looks like this:

    ```javascript
    import { Something } from '../src/something';

    const expect = chai.expect;

    describe('Something', () => {
        it('Should exist', () => {
            expect(Something).to.exist;
        });
    });
    ```

2. Create module `src/something.js` that looks like this:

    ```javascript
    export function Something() {}
    export const SOME_CONST = 123;
    ```

Then run karma with PhantomJS, and you will notice that it fails silently. If you take out this plugin from your karma config, it will work correctly. It also works fine if you comment out this line:

```javascript
// export const SOME_CONST = 123;
```

It took me a while to trace it down this far. Let me know if I can help further

**Comment by Victorystick** [comment]
@ccampbell See this PR gotwarlost/istanbul#507.

**Comment by artberri** [comment]
Thank you @Victorystick for your help!
