### ISSUE TITLE
istanbul ignore next not obeyed

### ISSUE THREAD

**Issue by jlami** [artberri/rollup-plugin-istanbul#20]
## Expected Behavior
`//istanbul ignore next` should be taken into account by the instrumenter

## Current Behavior
The coverage does not take the instructions into account, so coverage is lower than it should be.

## Steps to Reproduce
https://github.com/jlami/rollup-starter-project/tree/ignore-bug
This has an extra function at https://github.com/jlami/rollup-starter-project/blob/ignore-bug/lib/index.js#L41
But the coverage is only 50% of the functions when the test is run.

## Context (Environment)
Windows, but I don't think this will matter

**Comment by artberri** [comment]
Sorry for answering late but this not to be related with this repo but with istanbul.
