### ISSUE TITLE
source map not work

### ISSUE THREAD

**Issue by billowz** [artberri/rollup-plugin-istanbul#21]
## Current Behavior

1. isbanbul plugin print error on configuring the source map
```text
TypeError: instrumenter.lastSourceMap(...).toJSON is not a function
    at Object.transform (/test/node_modules/rollup-plugin-istanbul/dist/rollup-plugin-istanbul.cjs.js:30:58)
    at Promise.resolve.then (/test/node_modules/rollup/dist/rollup.js:15344:25)
```
2.  the `souceMap` option not work, need to config `instrumenterConfig.produceSourceMap`

## Steps to Reproduce

- isbanbul plugin plugin configuration
```js
istanbul({
	exclude: ['test/*'],
	sourceMap: true,
	instrumenterConfig: {
		produceSourceMap: true
	}
})
```

## Context (Environment)

 Windows 10, node v10.15.3

## Possible Implementation

1. [instrumenter.lastSourceMap](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/api.md#lastsourcemap) returns (null | Object) the source map object.
2. set [instrumenterConfig.produceSourceMap](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-instrument/api.md#parameters-1) on `ops.sourceMap` enabled

**Comment by billowz** [comment]
see rollup/rollup#2983, the istanbul-lib-instrument require the inputSourceMap to maps the not instrumented code back to it's original form

**Comment by tommck** [comment]
It seems that this was fixed https://github.com/rollup/rollup/pull/2993

Is this support added here yet?

**Comment by artberri** [comment]
The new version [3.0.0](https://github.com/artberri/rollup-plugin-istanbul/releases/tag/v3.0.0) that I've already published in the [npm registry](https://www.npmjs.com/package/rollup-plugin-istanbul) should fix the bug.

Thank you for the report.
