### ISSUE TITLE
line info incorrect buy vue3

### ISSUE THREAD

**Issue by songjiachao** [artberri/rollup-plugin-istanbul#27]
![image](https://user-images.githubusercontent.com/70792885/151505676-7eafa4f2-f063-4f45-8ba7-866333a9c89a.png)

**Comment by artberri** [comment]
I think that this problem has been fixed probably with the fix provided for https://github.com/artberri/rollup-plugin-istanbul/issues/24

If it hasn't, please provide a repository to reproduce the error before reopening the issue.
