### ISSUE TITLE
Fails silently when named exports are used

### ISSUE THREAD

**Issue by joerideg** [artberri/rollup-plugin-istanbul#3]
Thanks for the work! When using default export and import everything works great, however there is a problem when using named exports like:
`export var someVar = 'test';` 

karma then fails without error logged.

Named Imports are fine actually I can do `import { default as someVar } from './var';`

I've tested it out on your own sidr project and its the same case there.

**Comment by gscoppino** [comment]
https://github.com/gotwarlost/istanbul/issues/560
Once the next minor version of Istanbul is released, `rollup-plugin-Istanbul` will receive the fix with no changes as it uses caret range `Istanbul: '^0.4.2'`.

**Comment by joerideg** [comment]
Super thanks, i just traced it back to istanbul aswell by throwing a try catch statement around the 
`code = instrumenter.instrumentSync(code, id);` line

**Comment by artberri** [comment]
Thank you @gscoppino for detecting the source of the issue and thankyou @joerideg for reporting it!

**Comment by joerideg** [comment]
Your welcome! Now we wait :)
