### ISSUE TITLE
gives a lot of trouble if it works at all

### ISSUE THREAD

**Issue by Kflash** [artberri/rollup-plugin-istanbul#4]
Hi. Seems like this is not maintained anymore? Anyway. I get a lot of issues regarding this. The implementation is easy, but as mentioned in another issue ticket here. It fails silently - for me - most of the time.
Seems that I can't include and exclude files either as you can with Istanbul itself.
Also seems like this one is very strict. It doesn't work with *rollup-plugin-node-resolve*.

**Comment by jellymann** [comment]
@Kflash Have you tried excluding `node_modules` in the plugin options?

```js
// karma.conf.js
// ...
    rollupPreprocessor: {
      rollup: {
        plugins: [
          require("rollup-plugin-istanbul")({
            exclude: ["node_modules/**", "test/**/*.js"]
          }),
          require("rollup-plugin-node-resolve")(),
          require("rollup-plugin-babel")({
            exclude: "node_modules/**"
          })
        ]
      },
      bundle: {
        sourceMap: "inline"
      }
    },
// ...
```

**Comment by Kflash** [comment]
Hi. I tried it all. But still not figured out why the code dies silently. However you can't this things: 

```
Export default a = a + 1

Export default 123.
```

Plus other combos.  And you can import like this:

```
Import xxx from './'
```

You have too do:

```
Import xxx from './index'
```

And a lot of other things. 

Anyway. I know rollup very well. Just see the boilerplate on my repo. And I know rollup got a few limitations but it always output errors. But this dies silently. 

Even with the multi entry plugin etc nothing helped  however I git it working, but suddenly karma refuse to start.

**Comment by jellymann** [comment]
Sounds like an issue I had previously with the current version of karma-rollup-preprocessor. There is a bug in the currently published version where errors are not reported correctly, and karma just dies without reporting the error. Try using karma-rollup-preprocessor from github:
```json
"karma-rollup-preprocessor": "github:ulrik59/karma-rollup-preprocessor"
```
And it should show you the errors instead of failing silently.

**Comment by Kflash** [comment]
I got it working now. But still a issue with the multi entry plugin. Not sure if it's an issue with this plugin or the preprocessor.

**Comment by artberri** [comment]
Please, give us more info to reproduce the error, show us some code,... You are not giving us any clue, even you are saying that you don't know if the problem is with this plugin or not.

For more info go to https://github.com/artberri/rollup-plugin-istanbul/issues/8
