### ISSUE TITLE
Add support for Rollup 4

### ISSUE THREAD

**Issue by bershanskiy** [artberri/rollup-plugin-istanbul#53]
Issue tracker is **ONLY** used for reporting bugs. Use [stackoverflow](https://stackoverflow.com) for supporting issues and questions.

## Expected Behavior

`rollup-plugin-istanbul` works with `rollup` version 4, `npm` installs both easily.

## Current Behavior

`npm` produces the following error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: rollup-plugin-istanbul@4.0.0
npm ERR! Found: rollup@4.0.2
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"4.0.2" from the root project
npm ERR!   peerOptional rollup@"^2.78.0||^3.0.0||^4.0.0" from @rollup/plugin-node-resolve@15.2.2
npm ERR!   node_modules/@rollup/plugin-node-resolve
npm ERR!     dev @rollup/plugin-node-resolve@"15.2.2" from the root project
npm ERR!   4 more (@rollup/plugin-replace, @rollup/plugin-typescript, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional rollup@"^1.20.0||^2.0.0||^3.0.0" from rollup-plugin-istanbul@4.0.0
npm ERR! node_modules/rollup-plugin-istanbul
npm ERR!   dev rollup-plugin-istanbul@"4.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: rollup@3.29.4
npm ERR! node_modules/rollup
npm ERR!   peerOptional rollup@"^1.20.0||^2.0.0||^3.0.0" from rollup-plugin-istanbul@4.0.0
npm ERR!   node_modules/rollup-plugin-istanbul
npm ERR!     dev rollup-plugin-istanbul@"4.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

## Possible Solution

Test compatibility and then modify `package.json` key called `peerDependencies` -> `rollup` to allow for the new version, e.g., set it to `"^1.20.0||^2.0.0||^3.0.0||^4.0.0"`.

## Steps to Reproduce

1. Create package depending on `rollup` 4 and `rollup-plugin-istanbul`
2. Run `npm install`
3. Observe resolution failure

## Context (Environment)

Similar to #36.

## Detailed Description

Please see "Possible Solution".

## Possible Implementation

Please see "Possible Solution".

**Comment by artberri** [comment]
This is now fixed by https://github.com/artberri/rollup-plugin-istanbul/pull/54.

Thank you very much @bershanskiy for both, reporting and fixing it. I've just released the v5.0.0 version to NPM which supports Rollup v4 🎉
