### ISSUE TITLE
[Feature] Support `assert { type: 'json' }`

### ISSUE THREAD

**Issue by HarelM** [artberri/rollup-plugin-istanbul#60]
Plugin does not support `assert { type: 'json' }`?

## Expected Behavior

Build should pass

## Current Behavior

Build fails with the following error:
```
[!] (plugin istanbul) SyntaxError: /Users/harelmazor/dev/maplibre-gl-js/src/index.ts: Support for the experimental syntax 'importAttributes' isn't currently enabled (1:43):

> 1 | import packageJSON from '../package.json' assert { type: 'json' };
```
## Possible Solution

I'm not sure, is there a rollup plugin that removes this assetion?

## Steps to Reproduce

Add the plugin to a project that has this statement in the code.
I'm using typescript, so it might be related, IDK.

## Context (Environment)

I'm trying to add coverage to my e2e tests, this proves a lot harder than I thought as there are different kind of styles to code coverage.

## Detailed Description

Support this type of code, which I believe to be valid...?

## Possible Implementation

IDK, I'm not a rollup expert...

**Comment by artberri** [comment]
Hi @HarelM and sorry for the late reply.

This is not a bug, but a configuration issue. First of all you will probably need to use `@rollup/plugin-json` if you want to bundle the json file. And for the code instrumentation, you need to add the config to the instrumenter with the `instrumenterConfig` configuration option. Something like this should do the job:

```
	instrumenterConfig: {
		produceSourceMap: true,
		parserPlugins: [
			["importAttributes", { deprecatedAssertSyntax: true }],
		],
		generatorOpts: {
			importAttributesKeyword: "assert",
		},
	},
```

I've just added an example of using import assertions to one of the examples in this repo and it works:
https://github.com/artberri/rollup-plugin-istanbul/blob/main/examples/karma-ts/karma.conf.js

I'm sorry I couldn't answer you before, and this probably won't help you now, but just in case.

Thank you.

**Comment by HarelM** [comment]
I've found a different solution without using this plugin, but thanks anyway!
