### ISSUE TITLE
Using latest versions of istanbul?

### ISSUE THREAD

**Issue by brettz9** [artberri/rollup-plugin-istanbul#63]
## Expected Behavior

Not get errors when loading an instrumented file.

## Current Behavior

I get errors about an unexpected semi-colon (due to missing parentheses).

## Possible Solution

I don't know if perhaps `rollup-plugin-istanbul` is missing out on some patched updates (though maybe it is passing on a new buggy dependency).

## Steps to Reproduce

1. Clone https://github.com/es-joy/jsoe
2. Install `pnpm` if not already and run `pnpm install`
3. Run `pnpm instrument`
4. Run `pnpm start`
5. Open `http://127.0.0.1:8087/demo/index-instrumented.html` in the browser
6. Notice the console error about a missing semi-colon.

## Context (Environment)

I'm simply trying to instrument my files for use by Cypress.

## Detailed Description

Please let me know if there is something more detailed I can provide.

## Possible Implementation

Don't know.

**Comment by brettz9** [comment]
I confirmed the issue occurs with an upgrade of rollup from 4.18.1 to 4.19.0.

**Comment by brettz9** [comment]
So, not sure if this is an issue to report to rollup or to istanbul or to you?

**Comment by artberri** [comment]
Sorry for being so late on answering. This was a bug in Rollup not in this plugin: https://github.com/rollup/rollup/pull/5584, it is already fixed in newer versions.

Thank you anyway for reporting.
