### ISSUE TITLE
statements in disallowed (non-array) context 

### ISSUE THREAD

**Issue by Kflash** [artberri/rollup-plugin-istanbul#7]
Valid ES2015 syntax like this
```
export const ARRAY_ = [];
export const OBJECT_ = {};
```
end with this
`  Internal error: attempt to prepend statements in disallowed (non-array) context`

https://github.com/gotwarlost/istanbul/issues/632

**Comment by artberri** [comment]
This is not related with this plugin. Please read https://github.com/artberri/rollup-plugin-istanbul/issues/8
