### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Kflash** [artberri/rollup-plugin-istanbul#8]
Is this project dead?

**Comment by artberri** [comment]
@Kflash No, it is not dead.

I'm maintaining it, but I have another things to do also. You are opening a lot of issues without giving me error logs, code examples,... and seems that you are always in a rush. Most of them are not related with this plugin, did your read this other issue? 
https://github.com/artberri/rollup-plugin-istanbul/issues/3

Please read the following posts before opening more issues:
https://guides.github.com/activities/contributing-to-open-source/
http://wiki.civiccommons.org/Open_Source_Development_Guidelines/

Thank you.

**Comment by Kflash** [comment]
I always testing with istanbul and babel-istanbul too before I open an issue here. And when Istanbul plugin works just fine, and your plugin fails. And you claim it's not your plugin's fault, well....
